# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-23 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_author_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
